---
build_from:
  aarch64: "ghcr.io/hassio-addons/base/aarch64:stable"
  amd64: "ghcr.io/hassio-addons/base/amd64:stable"
  armhf: "ghcr.io/hassio-addons/base/armhf:stable"
  armv7: "ghcr.io/hassio-addons/base/armv7:stable"
  i386: "ghcr.io/hassio-addons/base/i386:stable"
codenotary:
  signer: "oliver@voelker.me"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Local Audio Play"
  org.opencontainers.image.description: "Play audio on the local hardware"
  org.opencontainers.image.source: "https://github.com/magenbrot/HomeAssistant_AddOns"
  org.opencontainers.image.licenses: "GNU General Public License v3.0"
